[app]
name = 'app'
env = 'production' # APP_ENV in local,production
url = 'http://localhost'
port = 9010
debug = false

[db]
migration = 'off' # OPEN_MIGRATION in on,off
connection = 'sqlite'# in mysql sqlite
url = 'db_user:db_pass@tcp(db_host:3306)/db_name?charset=utf8mb4&parseTime=True&loc=Local'
path = './storage/data/sqlite.db'# :memory:|./storage/data/sqlite.db

maxIdleConnections = 50
maxOpenConnections = 50
maxLifeSeconds = 300

[log]
type = 'stdout'# LOG_TYPE stdout,file
path = './storage/logs/thh.log'

[tspider]
output = './storage/tmp/'
screename = 'laravelphp'
max_spider_page = 4
downmedia = false
allusepush = false
onlymaster = true
proxy = 'http://localhost:11000'

[dbTool]
targetUrl = 'root:root_password@tcp(127.0.0.1:3306)/thh_database?charset=utf8mb4&parseTime=True&loc=Local'
originUrl = 'root:root_password@tcp(127.0.0.1:3306)/thh_database?charset=utf8mb4&parseTime=True&loc=Local'
dbConnect = 'dt/config/dbconnect'
output = './storage/model/'

[mkMdList]
targetDir = '/Users/thh/workspace/api-doc'
output = './storage/model/'

[PATH]
hexo = ''
workspace = ''