[app]
name = "app"
env = "production" # APP_ENV in local,production
url = "http://localhost"
port = 9010
outsitePort = 3097
debug = true

[log]
type = "stdout"# LOG_TYPE stdout,file
path = "./storage/logs/thh.log"

[db]
migration = "off" # OPEN_MIGRATION in on,off

[db.default]
connection = "sqlite"# in mysql sqlite
url = "root:root_password@tcp(127.0.0.1:3306)/thh_database?charset=utf8mb4&parseTime=True&loc=Local"
path = "./storage/data/sqlite.db"# :memory:|./storage/data/sqlite.db
maxIdleConnections = 50
maxOpenConnections = 50
maxLifeSeconds = 300

[db.local]
connection = "mysql"# in mysql sqlite
url = "root:root_password@tcp(127.0.0.1:3306)/thh_database?charset=utf8mb4&parseTime=True&loc=Local"
path = "./storage/data/sqlite.db"# :memory:|./storage/data/sqlite.db
maxIdleConnections = 50
maxOpenConnections = 50
maxLifeSeconds = 300

[spider.twitter]
output = "./storage/tmp/"
screenNameList = ["laravelphp"]
maxPage = 4
downmedia = false
allusepush = false
onlymaster = true
useProxy = true
proxy = "http://localhost:11000"
header = """
"""

[dbTool]
targetUrl = "root:root_password@tcp(127.0.0.1:3306)/thh_database?charset=utf8mb4&parseTime=True&loc=Local"
originUrl = "root:root_password@tcp(127.0.0.1:3306)/thh_database?charset=utf8mb4&parseTime=True&loc=Local"
dbConnect = "dt/config/dbconnect"
output = "./storage/model/"

[mkMdList]
targetDir = "/Users/thh/workspace/api-doc"
output = "./storage/model/"

[path]
hexo = ""
workspace = ""

[cq]
cqHttp="http://0.0.0.0:5700"